version: "3.8"

services:
  broadcast-service:
    image: "ikanji/broadcast-service:latest"
    depends_on:
      - redis
    
  browser-service:
    image: "ikanji/browser-service:latest"
    ports:
      - "3000:3000"
    depends_on:
      - redis

  nginx:
    image: "nginx"
    ports:
      - 8000:80
    volumes:
      - ./nginx/index.html:/var/www/html/index.html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
  
  redis:
    image: "redis:7.2.4-alpine"
    ports:
      - "6379:6379"
    command: redis-server --save 60 1 --loglevel warning
    volumes: 
      - rediscache:/data

volumes:
  rediscache:
    driver: local