version: "3.8"

services:
  broadcast-service:
    image: "broadcast-service:latest"
    depends_on:
      - redis
    
  browser-service:
    image: "browser-service:latest"
    ports:
      - "8080:8080"
    depends_on:
      - redis

  redis:
    image: "redis:7.2.4-alpine"
    ports:
      - "6379:6379"
    command: redis-server --save 60 1 --loglevel warning
    volumes: 
      - rediscache:/data

volumes:
  rediscache:
    driver: local